### ISSUE TITLE
Suppression de faux positifs

### ISSUE THREAD

**Issue by bguil** [papaamadou/projet_tutore#1]
Avec la commande:

`python corpuscorrection.py UD_French-GSD/fr_gsd-ud-dev.conllu voisin nil not_punct`

Le premier résultat est : 
`(('rajesh', 'secrétaire'), [0, 'bhagwan', '(', 'général']) {'NIL': [('fr-ud-dev_00006', '1', '15')], 'appos - L': [('fr-ud-dev_00006', 1, 4)]}`

Ce résultat est nécessairement un faux positif car, si on ajoutait la relation `appos - L` à la place de `NIL`, le même token `1` de la phrase `fr-ud-dev_00006` aurait deux gouverneurs. Il faudrait filter ces réponses.

**Comment by margotguettier** [comment]
nous avons ajouter une fonction qui filtre les résultats
